import { StyleSheet } from 'react-native';

export const editPropsStyles = StyleSheet.create({
    scroll: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 32,
    },
    actionContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 8,
        gap: 12,
        backgroundColor: '#fff',
    },
    buttonSecondary: {
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 8,
        flex: 1,
        alignItems: 'center',
    },
    buttonDanger: {
        backgroundColor: '#FEE2E2',
        borderWidth: 1,
        borderColor: '#FCA5A5',
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 8,
        alignItems: 'center',
    },
    buttonText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#374151',
        letterSpacing: 0.5,
    },
    buttonTextDanger: {
        fontSize: 16,
        fontWeight: '800',
        color: '#B91C1C',
        letterSpacing: 0.5,
    },
    headerTabs: {
        justifyContent: 'flex-start',
        flexDirection: 'row',
        flexWrap: 'wrap',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
        backgroundColor: '#fff',
        gap: 10,
    },
    tabButton: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 999,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: 'transparent',
    },
    tabButtonActive: {
        backgroundColor: '#111827',
        borderColor: '#111827',
    },
    tabText: {
        fontSize: 12,
        fontWeight: '500',
        color: '#6B7280',
    },
    tabTextActive: {
        color: '#FFFFFF',
    },
    propertyRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
        backgroundColor: '#FFFFFF',
    },
    propertyLabel: {
        fontSize: 13,
        fontWeight: '500',
        color: '#111827',
        flex: 1,
    },
    input: {
        minWidth: 110,
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        fontSize: 13,
        color: '#111827',
        backgroundColor: '#FAFAFA',
        textAlign: 'right',
    },
    inputSmall: {
        width: 60,
        paddingVertical: 4,
        paddingHorizontal: 6,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 6,
        fontSize: 13,
        textAlign: 'center',
        backgroundColor: '#FAFAFA',
    },
    stepContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    stepBtn: {
        width: 28,
        height: 28,
        borderRadius: 6,
        backgroundColor: '#F3F4F6',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    colorPickerOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    colorPickerContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        width: '85%',
        maxWidth: 320,
    },
    colorPickerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    colorPickerTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
    },
    colorPickerClose: {
        fontSize: 20,
        color: '#6B7280',
        padding: 4,
    },
    colorButton: {
        width: 60,
        height: 40,
        borderRadius: 8,
        borderWidth: 2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    colorValue: {
        fontSize: 10,
        fontWeight: '600',
        color: '#fff',
        textShadowColor: 'rgba(0,0,0,0.5)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 1,
    },
    selectButton: {
        minWidth: 110,
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        backgroundColor: '#FAFAFA',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    selectButtonText: {
        fontSize: 13,
        color: '#111827',
        fontWeight: '500',
    },
    selectDropdown: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        marginTop: 4,
        overflow: 'hidden',
        maxHeight: 180,
    },
    selectOption: {
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    selectOptionActive: {
        backgroundColor: '#F3F4F6',
    },
    selectOptionText: {
        fontSize: 13,
        color: '#6B7280',
    },
    selectOptionTextActive: {
        color: '#111827',
        fontWeight: '600',
    },
});
